# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-28 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_userextend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextend',
            name='user_fb_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
